nmake /f Makefile.win help
nmake /f Makefile.win install
nmake /f Makefile.win dev
nmake /f Makefile.win dashboard
nmake /f Makefile.win cert
nmake /f Makefile.win lint
nmake /f Makefile.win format
nmake /f Makefile.win test
nmake /f Makefile.win doctor
nmake /f Makefile.win clean
