<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>ProjectPilotAI CI/CD Report</title>
  <style>
    body { font-family: 'Segoe UI', sans-serif; margin: 2rem; background: #f7f7f7; color: #333; }
    h1, h2 { color: #222; }
    pre { background: #f0f0f0; padding: 1rem; border-radius: 6px; overflow-x: auto; }
    .job-block { margin-bottom: 3rem; }
    .footer { margin-top: 4rem; font-size: 0.9rem; color: #777; }
  </style>
</head>
<body>
  <h1>🚀 ProjectPilotAI CI/CD Report Viewer</h1>

  <div class="job-block">
    <h2>🧮 Homework Pipeline</h2>
    <p>This pipeline performs: <strong>Add 3 + 7</strong> → <strong>× 9</strong> → <strong>Print Result</strong></p>
    <pre><code>
job_1: echo $((3 + 7)) → math-homework.txt
job_2: cat math-homework.txt → value × 9 → new math-homework.txt
job_3: cat math-homework.txt → print "🧠 The result is: $value"
    </code></pre>
  </div>

  <div class="job-block">
    <h2>🧪 Matrix Artifact Upload</h2>
    <p>Generated on <code>ubuntu</code>, <code>macOS</code>, and <code>windows</code></p>
    <pre><code>
upload: echo "hello from ${{ matrix.os }}" > file-${{ matrix.os }}.txt
download: download artifacts → merged into /my-artifacts/
    </code></pre>
  </div>

  <div class="footer">
    Generated by <strong>ProjectPilotAI</strong> — view CI Logs:
    <a href="https://github.com/Web4application/project_pilot_ai/actions" target="_blank">GitHub Actions</a>
  </div>
</body>
</html>
